[model]
hidden_sizes = [1000, 1000, 1000]
epochs = 10000
loss_threshold = 1
damping_factor = 0.7
epsilon = 0.00000001
learning_rate = 0.00005
skip_profiling = 1
should_log_metrics = true 
should_replace_neg_data = false

[device]
device = "mps"

